name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_REMOTES_STANDALONE: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: install `RSelenium`
        run: |
          Rscript -e "install.packages('remotes')" -e "remotes::install_github('ropensci/RSelenium')"
